server:
  port: 8080

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    order-service:
      path: /order/**
      url: http://127.0.0.1:9091/

shuaicj.security.jwt.secret: otherpeopledontknowit
